### ISSUE TITLE
'/factorio/entrypoints': File exists

### ISSUE THREAD

**Issue by jbolm** [dtandersen/docker_factorio_server#143] opened 2018-03-14 18:03 UTC
When attempting to update from 0.16.29 to 0.16.30 (either by calling the specific version tag, using the latest tag, or even the 0.16-dev tag), I see the following in my log:

```
+ set -e
+ id
uid=845(factorio) gid=845(factorio) groups=845(factorio)
+ mkdir -p /factorio/saves
+ mkdir -p /factorio/config
+ mkdir -p /factorio/mods
+ mkdir -p /factorio/scenarios
+ mkdir -p /factorio/entrypoints
mkdir: can't create directory '/factorio/entrypoints': File exists
```
I'm running this on my unRaid server. The command that runs is:

```
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="Factorio_Personal" --net="bridge" -e TZ="America/Denver" -e HOST_OS="unRAID" -p 34301:34197/udp -p 34301:27015/tcp -v "/mnt/user/appdata/factorio_personal/config/":"/opt/factorio/config":rw -v "/mnt/user/appdata/factorio_personal/mods/":"/opt/factorio/mods":rw -v "/mnt/user/appdata/factorio_personal/saves/":"/opt/factorio/saves":rw dtandersen/factorio:latest
```

The server runs fine if I roll back to 0.16.29.

**Comment by dtandersen** [comment] 2018-03-14 20:14
`ls -al` your /opt/factorio/entrypoints folder or wherever your stuff is. Is /factorio/entrypoints a file instead of a directory?

**Comment by dtandersen** [comment] 2018-03-14 20:17
Took out 

```
+ mkdir -p /factorio/scenarios
+ mkdir -p /factorio/entrypoints
```

in dev version, but would be nice to know what caused it.

**Comment by jbolm** [comment] 2018-03-14 20:33
nope, no entrypoints folder:

```
drwxrwxrwx 1 nobody users   30 Mar 14 14:19 ./
drwxrwxrwx 1 nobody users  566 Mar 14 11:22 ../
drwxrwxrwx 1    999   999  164 Mar  9 11:53 config/
drwxrwxrwx 1    999   999 1634 Mar 14 11:56 mods/
drwxrwxrwx 1    999   999  156 Mar 14 11:57 saves/
```

I created a fresh server using the latest tag to see if maybe something was corrupt on my end and it's giving the same error.

Currently waiting for the updated dev versions to build, then I'll give that a try and update this thread.

**Comment by jbolm** [comment] 2018-03-14 21:38
The 0.16-dev build finished. I updated my config to use this build and everything started up just fine.

**Comment by yukihyou** [comment] 2018-03-16 04:03
/factorio/entrypoints was a file on my server, containing what appeared to be the launch script. Because it was in the volume, it wasn't removed on update. I deleted the file manually and it started up fine after that, creating an empty directory.

**Comment by muehre** [comment] 2018-03-18 22:45
+1
Are you planning to tag the fix as latest? The latest version is not useable for me atm. 😢

**Comment by yukihyou** [comment] 2018-03-18 22:47
You should be able to remove the file manually in the meantime.

**Comment by jbolm** [comment] 2018-03-19 01:50
@yukihyou - there is no entrypoints file or folder on my server to remove. I just wiped everything and re-pulled the image for the 'latest' tag and it has the same error. The change that dtanderson made to the 0.16-dev build resolved the issue for me.

I'm running this on unraid, if that makes any difference.

**Comment by yukihyou** [comment] 2018-03-19 14:26
The `/factorio` directory is marked as a volume, which means it persists data - this allows your save to remain between updates of the docker image. The `entrypoints` file is in the same parent location as the saves.

At a glance, I believe these lines are responsible for creating `entrypoints` as a file and not a directory as intended, as they are missing the trailing slash, and previously the directory was not created prior to these commands being run:
```
COPY ./scenario2map.sh /factorio/entrypoints
COPY ./scenario.sh /factorio/entrypoints
```

I've not used unraid, but if you can find where your save file is located on the host, there is likely to be a file `../entrypoints` relative to the saves, which would need to be removed.

**Comment by dtandersen** [comment] 2018-03-19 17:07
Pushed a few changes to the master branch (0.16-dev) https://github.com/dtandersen/docker_factorio_server/commit/66bef56cd26a2812254f3495a1dc70c86b901dcd

It has been decreed that entrypoints live in /. Updated docs accordingly. Entrypoints no longer show up in the volume.

If for some reason a custom entrypoint is wanted mount it.

**Comment by jbolm** [comment] 2018-03-20 02:51
Updated to the latest 0.16-dev version - no issues on my end.

**Comment by bplein** [comment] 2018-03-23 13:37
Agreed, when I made those entrypoint changes, they worked and made sense but were probably dependent on some pre-existing configuration in my setup.

**Closed** 2019-05-05 01:31 UTC
